import ReadingPath from '@/components/ReadingPath';
import { Language } from '@/lib/types';

export function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'fr' }];
}

const content = {
  en: `
    <h1 style="font-size: 2.25rem; line-height: 1.1; margin-bottom: 2rem; font-weight: 700; letter-spacing: -0.025em; color: #000;">Principles & Boundaries</h1>
    <h2 style="font-size: 1.5rem; line-height: 1.3; margin-bottom: 1rem; font-weight: 600; color: #000;">Principles, perimeters and excluded objectives</h2>
    <p style="font-size: 1.125rem; line-height: 1.625; color: #18181b; margin-bottom: 1.5rem;">Reconstruction is valuable, until it becomes the subject of dispute. These principles are not design preferences. They exist because, in formal examination contexts, flexibility becomes a vulnerability: evidence must be created at the time of execution, not reconstructed post-hoc.</p>
    <p style="font-size: 1.125rem; line-height: 1.625; color: #18181b; margin-bottom: 1.5rem;">We use the term <strong>Execution Evidence Infrastructure (EEI)</strong> to describe this framework: a dedicated evidence layer that creates examinable facts at the moment of execution, independent of subsequent audits, inquiries, or reconstructions.</p>
    <section style="margin-top: 2.5rem;"><hr style="border: none; border-top: 1px solid #e4e4e7; margin-bottom: 2rem;" /></section>
    <h3 style="font-size: 1.25rem; font-weight: 500; letter-spacing: -0.025em; color: #000; margin-bottom: 1rem;">Non-negotiable principles</h3>
    <ul style="list-style: none; padding-left: 0; margin-left: 0.25rem; border-left: 1px solid #e4e4e7; margin-bottom: 1.5rem;">
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.75rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span><strong>Evidence at Time T (Point of no return)</strong><br>Prevents retrospective reconstruction from becoming "the evidence" by producing facts at the exact moment the action occurs. This protects the organization against asymmetric adverse interpretations by anchoring the defense in the actual execution context, effectively neutralizing hindsight bias.</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.75rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span><strong>Append-only Ledger: An immutable, cumulative record</strong><br>Nothing is ever erased or overwritten. If new information (e.g., an audit or post-hoc validation) emerges after an execution, it is appended as a new timestamped artefact. We do not modify the past; we document the progression of knowledge.</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.75rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span><strong>Agent-Agnostic (Human or Machine)</strong><br>Preserves a single factual chain between automated decisions and human interventions, without loss of continuity.</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.75rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span><strong>Non-intrusiveness (Functional Decoupling)</strong><br>Ensures that evidence capture does not act as a checkpoint. The system is purely observational: it modifies neither outcomes nor workflows, and minimizes system overhead.</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.75rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span><strong>Strict Separation: Execution vs. Evaluation</strong><br>Distinguishes "what happened" from "what was evaluated," so that subsequent examination can separate the raw action from its organizational interpretation.</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.75rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span><strong>Independent Verification (Including Offline)</strong><br>Integrity can be verified from exported evidence artefacts (evidence packages) without relying on the source systems, and without requiring access to the execution environment during critical examinations.</span></li>
    </ul>
    <section style="margin-top: 2.5rem;"><hr style="border: none; border-top: 1px solid #e4e4e7; margin-bottom: 2rem;" /></section>
    <h3 style="font-size: 1.25rem; font-weight: 500; letter-spacing: -0.025em; color: #000; margin-bottom: 1rem;">Deliberate Exclusions</h3>
    <p style="font-size: 1.125rem; line-height: 1.625; color: #18181b; margin-bottom: 1.5rem;">These exclusions preserve Horizon's role as a pure evidence layer, orthogonal to operational tools:</p>
    <ul style="list-style: none; padding-left: 0; margin-left: 0.25rem; border-left: 1px solid #e4e4e7; margin-bottom: 1.5rem;">
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.5rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span>Not an investigation platform</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.5rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span>Not observability or SIEM</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.5rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span>Not a case-management workflow</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.5rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span>Not a compliance tool (GRC)</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.5rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span>Not a single operational oversight console</span></li>
    </ul>
    <section style="margin-top: 2.5rem;"><hr style="border: none; border-top: 1px solid #e4e4e7; margin-bottom: 2rem;" /></section>
    <h3 style="font-size: 1.25rem; font-weight: 500; letter-spacing: -0.025em; color: #000; margin-bottom: 1rem;">Why logs and tickets are not equivalent</h3>
    <p style="font-size: 1.125rem; line-height: 1.625; color: #18181b; margin-bottom: 1.5rem;">Logs and tickets facilitate reconstruction. They do not create a declared, ordered, and immutable evidence record at Time T. When an examination focuses on a specific case, the question is no longer "what usually happens," but "what exactly happened here." At that point, the reconstruction itself becomes contestable.</p>
  `,
  fr: `
    <h1 style="font-size: 2.25rem; line-height: 1.1; margin-bottom: 2rem; font-weight: 700; letter-spacing: -0.025em; color: #000;">Principes & Limites</h1>
    <h2 style="font-size: 1.5rem; line-height: 1.3; margin-bottom: 1rem; font-weight: 600; color: #000;">Principes, périmètres et objectifs exclus</h2>
    <p style="font-size: 1.125rem; line-height: 1.625; color: #18181b; margin-bottom: 1.5rem;">La reconstruction est précieuse, jusqu'à ce qu'elle devienne l'objet de la contestation. Ces principes ne sont pas des préférences de conception. Ils existent car, dans les contextes d'examen formel, la flexibilité devient une vulnérabilité : la preuve doit être créée au moment de l'exécution, et non reconstruite a posteriori.</p>
    <p style="font-size: 1.125rem; line-height: 1.625; color: #18181b; margin-bottom: 1.5rem;">Nous utilisons le terme <strong>Infrastructure de Preuve d'Exécution (EEI)</strong> pour décrire ce dispositif : une couche de preuve dédiée qui crée des faits examinables au moment de l'exécution, indépendamment des audits, enquêtes ou reconstructions ultérieurs.</p>
    <section style="margin-top: 2.5rem;"><hr style="border: none; border-top: 1px solid #e4e4e7; margin-bottom: 2rem;" /></section>
    <h3 style="font-size: 1.25rem; font-weight: 500; letter-spacing: -0.025em; color: #000; margin-bottom: 1rem;">Principes non négociables</h3>
    <ul style="list-style: none; padding-left: 0; margin-left: 0.25rem; border-left: 1px solid #e4e4e7; margin-bottom: 1.5rem;">
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.75rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span><strong>La preuve à l'instant T (point de non-retour)</strong><br>Empêche la reconstruction rétrospective de devenir « la preuve » en produisant des faits au moment même où l'action survient. Cela protège l'organisation contre les interprétations adverses asymétriques en ancrant la défense sur le contexte réel de l'exécution, neutralisant ainsi le biais de rétrospective.</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.75rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span><strong>Registres en ajout exclusif (Append-only) : Un registre immuable et cumulatif</strong><br>Rien n'est jamais effacé ou réécrit. Si une information nouvelle (ex : un audit ou une validation a posteriori) survient après une exécution, elle est ajoutée comme un nouvel artefact daté. On ne modifie pas le passé, on documente la progression de la connaissance.</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.75rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span><strong>Agnostique vis-à-vis de l'agent (humain ou machine)</strong><br>Préserve une chaîne factuelle unique entre les décisions automatisées et les interventions humaines, sans rupture de continuité.</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.75rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span><strong>Non-intrusivité (découplage fonctionnel)</strong><br>Garantit que la capture de la preuve n'agit pas comme un point de contrôle. Le dispositif est purement observationnel : il ne modifie ni les résultats ni les flux de travail, minimisant ainsi la charge système.</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.75rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span><strong>Séparation stricte : exécution vs évaluation</strong><br>Distingue « ce qui s'est passé » de « ce qui a été évalué », afin que l'examen ultérieur puisse séparer l'action brute de son interprétation organisationnelle.</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.75rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span><strong>Vérification indépendante (y compris hors ligne)</strong><br>L'intégrité peut être vérifiée à partir d'artefacts exportés (dossiers de preuves) sans dépendre des systèmes d'origine, ni nécessiter d'accès à l'environnement d'exécution au moment de l'examen.</span></li>
    </ul>
    <section style="margin-top: 2.5rem;"><hr style="border: none; border-top: 1px solid #e4e4e7; margin-bottom: 2rem;" /></section>
    <h3 style="font-size: 1.25rem; font-weight: 500; letter-spacing: -0.025em; color: #000; margin-bottom: 1rem;">Objectifs exclus délibérément</h3>
    <p style="font-size: 1.125rem; line-height: 1.625; color: #18181b; margin-bottom: 1.5rem;">Ces exclusions préservent le rôle d'Horizon en tant que couche de preuve pure, orthogonale aux outils opérationnels :</p>
    <ul style="list-style: none; padding-left: 0; margin-left: 0.25rem; border-left: 1px solid #e4e4e7; margin-bottom: 1.5rem;">
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.5rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span>Ni plateforme d'enquête</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.5rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span>Ni observabilité ou SIEM</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.5rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span>Ni flux de gestion de dossiers (case-management)</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.5rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span>Ni outil de conformité (GRC)</span></li>
      <li style="display: flex; align-items: baseline; gap: 0.75rem; margin-bottom: 0.5rem; padding-left: 1.25rem; font-size: 1.125rem; line-height: 1.625; color: #18181b;"><span style="font-size: 0.75rem; color: #a1a1aa;">■</span><span>Ni console de supervision opérationnelle</span></li>
    </ul>
    <section style="margin-top: 2.5rem;"><hr style="border: none; border-top: 1px solid #e4e4e7; margin-bottom: 2rem;" /></section>
    <h3 style="font-size: 1.25rem; font-weight: 500; letter-spacing: -0.025em; color: #000; margin-bottom: 1rem;">Pourquoi les logs et les tickets ne sont pas équivalents</h3>
    <p style="font-size: 1.125rem; line-height: 1.625; color: #18181b; margin-bottom: 1.5rem;">Les logs et les tickets facilitent la reconstruction. Ils ne créent pas une preuve déclarée, ordonnée et immuable à l'instant T. Lorsqu'un examen porte sur un cas spécifique, la question n'est plus « que se passe-t-il habituellement », mais « que s'est-il passé exactement ici ». C'est à ce moment précis que la reconstruction elle-même devient contestable.</p>
  `
};

export default function PrinciplesBoundariesPage({ params }: { params: { lang: Language } }) {
  return (
    <article className="max-w-3xl">
      <div dangerouslySetInnerHTML={{ __html: content[params.lang] }} />
      <ReadingPath currentSlug="principles-boundaries" lang={params.lang} />
    </article>
  );
}
